baseURL = "http://localhost:1313/acnil/"
# baseURL = "/"
languageCode = 'es-es'
title = 'ACNIL'
description = ''

mainSections = "blog"

RelativeURLs=true
CanonifyURLs=true

# I based the website on this, but I removed all unnecessary code to make it easier to understand
# https://github.com/nanxiaobei/hugo-paper
# theme = "paper"

refLinksErrorLevel="WARNING"

[menu]
[[menu.main]]
  name = 'Inicio'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'BigBangBurgos'
  pageRef = '/jornadas'
  weight = 20
[[menu.main]]
  name = 'Asociaci√≥n'
  pageRef = '/about'
  weight = 30

[params]
  # header social icons
  twitter = 'acnilburgos'               
  instagram = 'acnilburgos'           
  github = 'acnil'

  # home page profile
  # avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  # name = 'YOUR_NAME'
  # bio = 'YOUR_BIO'


  # misc
  monoDarkIcon = true                     # show monochrome dark mode icon

[markup.goldmark.renderer]
unsafe= true
